/**
 * Named route constants for expo-router's typed routes.
 * Keeps navigation calls (`router.push(Routes.X)`) free of raw string typos.
 */
export const Routes = {
  auth: {
    splash: '/(auth)',
    welcome: '/(auth)/welcome',
    signup: '/(auth)/signup',
    otp: '/(auth)/otp',
    pinCreate: '/(auth)/pin-create',
    biometrics: '/(auth)/biometrics',
    kyc: '/(auth)/kyc',
    kycPending: '/(auth)/kyc-pending',
  },
  consumer: {
    home: '/(consumer)',
    notifications: '/(consumer)/notifications',
    scan: '/(consumer)/scan',
    scanMerchant: '/(consumer)/scan/merchant',
    scanAmount: '/(consumer)/scan/amount',
    scanSource: '/(consumer)/scan/source',
    scanSplit: '/(consumer)/scan/split',
    scanConfirm: '/(consumer)/scan/confirm',
    scanProcessing: '/(consumer)/scan/processing',
    scanSuccess: '/(consumer)/scan/success',
    scanFailed: '/(consumer)/scan/failed',
    sources: '/(consumer)/sources',
    sourcesBank: '/(consumer)/sources/bank',
    sourcesWallet: '/(consumer)/sources/wallet',
    sourcesUsd: '/(consumer)/sources/usd',
    sourcesCrypto: '/(consumer)/sources/crypto',
    history: '/(consumer)/history',
    rewards: '/(consumer)/rewards',
    rewardsRedeem: '/(consumer)/rewards/redeem',
    rewardsTiers: '/(consumer)/rewards/tiers',
    security: '/(consumer)/security',
    securityPinChange: '/(consumer)/security/pin-change',
    securityLimits: '/(consumer)/security/limits',
    securityDevices: '/(consumer)/security/devices',
    profile: '/(consumer)/profile',
    profileSettings: '/(consumer)/profile/settings',
    profileRates: '/(consumer)/profile/rates',
    profileSupport: '/(consumer)/profile/support',
  },
  merchant: {
    home: '/(merchant)',
    payments: '/(merchant)/payments',
    analytics: '/(merchant)/analytics',
    settlement: '/(merchant)/settlement',
    qr: '/(merchant)/qr',
    settings: '/(merchant)/settings',
    onboardingSignup: '/(merchant)/onboarding/signup',
    onboardingKyc: '/(merchant)/onboarding/kyc',
    onboardingSettlementSetup: '/(merchant)/onboarding/settlement-setup',
    onboardingQrSetup: '/(merchant)/onboarding/qr-setup',
  },
} as const;
